### ISSUE TITLE
Apple original 1978 Serial Interface card

### ISSUE THREAD

**Issue by Verault** [ADTPro/adtpro#108]
I own two of the original Apple Serial Interface cards 820-0008 (670-x005) and have had no success at getting ADTPro working them them. I have been trying 19200 Baud as well as other settings.

Has ADTPro been tested with this Apple Card? Am I missing some obvious setting or dipswitch? I figure this would be a relatively common apple branded serial card.

**Comment by david-schmidt** [comment]
Hi there - despite being from Apple and being serial, it is in no way compatible with the Super Serial card (or ADTPro), sorry to say.  There was a version of the original ADT that could use the Communications Card - it is called ADTCC.  You can find that in the legacy part of the old ADT distribution:
https://github.com/david-schmidt/adt/releases/tag/v2.4

The `legacy/src/client/cc/Misc/ADT_SC.DSK` disk image contains the CC binary.  I'm not entirely sure if it would work with modern ADTPro - I've never tried it, as I've never seen a CC in the wild.  They didn't have the market penetration that the Super Serial card did, partly due to its slow speed.  And the odd/slow speeds the CC has don't match up with what we run with in ADTPro now.  You might be able to hook it up to an older PC DOS version of the ADT server.  Anyway, some additional notes on the CC and setting it up:
https://mirrors.apple2.org.za/ground.icaen.uiowa.edu/ANN/adtcc.fid
