### ISSUE TITLE
Executing disk images (without writing floppy)

### ISSUE THREAD

**Issue by sprive** [ADTPro/adtpro#115]
I've successfully booted a IIc over serial from a Mac Mini (seemingly at 115K, nice). I do not own any 5.25 floppies, but this IIc will boot off an external 3.5 floppy (and I have only a few).

1. What I would like to do is run games or applications from disk images, booted over serial, without having to record a floppy disk.  Is this possible at all, and what would be an example image to try?
1. Is the ADTPro use case mainly data transfer, meaning I can boot ProDOS this way (but don't even bother trying games)?
1. Just in case.. I haven't overlooked any FAQ? I found none.

I have ordered a virtual floppy device which is probably the way to go, but until it arrives I'm curious about this option.
Thanks!

**Comment by david-schmidt** [comment]
What you're describing is not a use for ADTPro, but for something like the Apple II Game Server:
https://sourceforge.net/projects/a2gameserver/
It's not really maintained any more unfortunately, so that will be more of a chore to get going.  But there is an audio alternative that branched off of the a2gameserver ideas:
http://asciiexpress.net/gameserver/

That line of thinking is about single-loading games over a wire, vs. ADTPro which is intended to move entire disk images back and forth.
