### ISSUE TITLE
ADTPro Tries to use card in slot 1

### ISSUE THREAD

**Issue by toml12953** [ADTPro/adtpro#27]
I have two serial cards in my Apple IIe. There's one in slot 1 for the ImageWriter II and one in slot 2 for file transfers. When I run ADTPro I get as far as
ADTPRO SERIAL BOOTSTRAPPER
FOUND SLOT 1
LOADING MLI:

then nothing happens. I really don't want to have to remove my card in slot 1 every time I want to transfer a file. Is there any way to get ADTPro to use the card in slot 2 exclusively?

**Comment by david-schmidt** [comment]
Hopefully, you only ever have to bootstrap ADTPro once; having done that, you should write out a floppy and use that (configuring to explicitly use slot 2, instead of trying to discover its own).  Speediboot isn't configurable; it's algorithm is to use the lowest-numbered valid serial port it finds.  But ADTPro is configurable with a saveable slot - you set it, save the config, and it'll use that from then on.  See:
http://adtpro.com/configserial.html

If you still want to bootstrap, you can't use Speediboot because it'll always land on slot 1; but the older, manual bootstrap process will work for you:
http://adtpro.com/bootstrap.html#If_Speediboot_doesnt_work_for_you
