### ISSUE TITLE
Host timeout

### ISSUE THREAD

**Issue by philgoetz** [ADTPro/adtpro#44]
I got ADTPro running on my //c, but when I choose (D)IR, then hit RETURN at the FILENAME prompt, I get

WAITING FOR HOST REPLY, ESC CANCELS

which is replaced 2 seconds later with

HOST TIMEOUT
PRESS A KEY TO CONTINUE...

This happens whether I set client and server to 19200 or 115200 baud. I don't know any other parameters I can adjust.

**Comment by david-schmidt** [comment]
Hi, Phil -

This is because there isn't a fully functioning serial connection between your //c and your host.  Assuming you've plugged your RetroFloppy-supplied DIN5 cable into the modem port of your //c, we now need to worry about the connection to your host computer, whether or not it sees the appropriate communications port, and so on.  Lots more details are needed to help diagnose here.

**Comment by philgoetz** [comment]
Is that possible even though I just sent ProDOS and ADTPro over that serial connection using Bootstrapping?

Windows reports that the USB-SERIAL CH340 device on COM5 is working, the driver is signed, and the ADTPro server says it has a connection.

**Comment by david-schmidt** [comment]
It's possible if you actually did push those two things individually and didn't do Speediboot.  Speediboot will test bi-directional communications in the process.  If Speediboot doesn't work, then your connection isn't going to work - and I suspect your CH340 is bad.

**Comment by philgoetz** [comment]
I ordered another serial-to-USB connector, based on a different chip, which should arrive within a week.  I think I'll put this on hold until I get it.
