### ISSUE TITLE
Macintosh plus support?

### ISSUE THREAD

**Issue by Tommy51389** [ADTPro/adtpro#66]
Appreciate all the work that has been done on this project. I am just wondering if there is any way to use this project on a Macintosh plus?

**Comment by david-schmidt** [comment]
Hi, Tommy -

There was an old Pre-ADTPro project that ran on the Mac Plus, back in the ADT era.  It's called MacADT.  The .sit of that is packaged as part of the latest ADT, downloadable here:
https://github.com/david-schmidt/adt/releases/download/v2.4/ADT_2007_2.zip

The current software isn't going to ever run on the MacOS platform because it can't/doesn't support the Java level necessary.
